### ISSUE TITLE
Documentation: Provide overview of "Insiders only" features

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#1949]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

It would be nice if the documentation included a short list of features that are Insiders only, preferably on the [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) page.

Not only for the benefit of members of the Insiders program, but also to trigger some FOMO among non-members ;-)

Right now, I have to browse through all pages to find those features. Searching for "insiders only" doesn't work well.

**Comment by squidfunk** [comment]
Have you seen the roadmap, which lists all features in their respective tiers?
https://squidfunk.github.io/mkdocs-material/insiders/#roadmap

**Comment by wilhelmer** [comment]
Hmm okay, we could use this, but atm the list is not complete (color palette toggle is missing, maybe more?). Also, links to the corresponding feature descriptions would be nice.

**Comment by squidfunk** [comment]
I had a discussion with a colleague about this exact topic, so maybe you're right and it's beneficial to add a feature-wise side-by-side comparison. After I've finished my refactoring spree, I'm going to take another look at the landing page, as I guess we could add a comparison table highlighting the benefits of using Insiders.

**Comment by wilhelmer** [comment]
Here's a proposal - just an outline with dummy links to get the idea.

## Available Features

The following list shows which features are currently only available in Material for MkDocs Insiders.

- [x] Highlighting of matched search terms in content area ([docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#highlighting-search))
- [x] Navigation can always be expanded via configuration ([docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#highlighting-search))
- [x] Header can be automatically hidden on scrolling ([docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#highlighting-search))
- [x] Table of contents can be automatically hidden when empty ([docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#highlighting-search))
- [x] Support for user-toggleable themes ([docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#highlighting-search))

## Roadmap

The following list shows which features will be made publicly available if the funding goals – named after varieties of chili peppers 
[I'm growing on my balcony][11] – are reached.

  [11]: https://www.instagram.com/squidfunk/

### Prairie Fire

Funding goal: __$1,000__
Status: _exclusive_

New features and improvements for _content and toc_, including:

- Highlighting of matched search terms in content area
- Navigation can always be expanded via configuration
- Header can be automatically hidden on scrolling
- Table of contents can be automatically hidden when empty
- Table of contents can be moved into navigation for more space
- Table of contents shows which sections have search results
- Table of contents auto-collapses and expands only the active section
- Better support for wide screens, i.e. more horizontal space
- ... more to come

[...]

**Comment by wilhelmer** [comment]
The basic assumption is that users are more interested in the short-time benefits of participating in the program than the long-term benefits of donating towards a funding goal.

**Comment by squidfunk** [comment]
Thanks for the draft! You're absolutely right that it makes sense to better point out what's in for the user. I would dare to say that it works pretty well already (given that there are already 26 sponsors), but there's always room for improvement. What I want to avoid is that users think "ugh, this costs money to use it", which is why my current strategy is to sprinkle the features across the docs, all linking back to the Insiders page. It's free for use after all, only when you want to have specific features, you would need to become a sponsor. However, I agree that the Insiders page could be a little more clear on what you get. It's an ongoing effort 😊

**Comment by squidfunk** [comment]
Added in 032bdb2b – thanks for the suggestions!
