### ISSUE TITLE
Documentation: Improve meta tags documentation

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#2609]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

The [meta tags documentation](https://squidfunk.github.io/mkdocs-material/reference/meta-tags/) doesn't provide complete information on how to add custom meta tags using the Metadata extension.

Defining a custom front matter in a topic as described isn't sufficient to include custom meta tags in the HTML output. Additionally, you must add your tags to `base.html` with something like

```jinja
{% block site_meta %}
{{ super() }}
{% if page and page.meta.mycustomtag %}
<meta name="mycustomtag" content="{{ page.meta.mycustomtag }}" />
{% endif %}
{% endblock %}
```

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for creating! A great addition to the docs!

**Comment by squidfunk** [comment]
Restructured the meta tags documentation in 4feba2ebc - I adjusted the snippet from the OP to use `extrahead` instead.
