### ISSUE TITLE
🚀 Material for MkDocs 8 – Beta

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#3219]
__With the help of my awesome sponsors, I'm happy to announce that the '[Ghost Pepper](https://squidfunk.github.io/mkdocs-material/insiders/#4000-ghost-pepper)' funding goal has been reached, which means that [code annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations), [anchor tracking](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking) and [versioning warnings](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#version-warning) are finding their way into this repository!__

Since those are some pretty nifty features, it's a good time to wrap them up into a new major release and drop some long-standing deprecated features. This issue will track the progress on the road from the beta to the final release of version 8.

__If you experience any problems, for now, please report them as a comment in this issue__.

## Installation

```
pip install mkdocs-material==8.0.0b2
```

Note that this is a beta release.

### Added

- [__Code annotations__](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations): this is probably the most anticipated new feature. After finishing the merge and deprecations, I'll revisit the [placement issues on mobile](https://github.com/squidfunk/mkdocs-material/issues/2475). Those need to get fixed before we push out the major release.

- [__Version warning__](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#version-warning) and [__Anchor tracking__](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking)
### Improved

- __Content partials__: there's now a new partial, which allows fpr customizing the appearance of the Markdown content without overriding `base.html`. This makes it easy to add a further button to the top of a page or to add arbitrary content to the footer of a page:

    ``` jinja2
    {% block content %}
      {% include "partials/content.html" %}
    {% endblock %}
    ```

- __Copyright partial__: the copyright has been moved into a separate partial, which lifts the need to override the `footer.html` template when changing the copyright information.

    ``` jinja2
    <div class="md-footer-meta md-typeset">
      <div class="md-footer-meta__inner md-grid">
        {% include "partials/copyright.html" %}

        <!-- Social links -->
        {% if config.extra.social %}
          {% include "partials/social.html" %}
        {% endif %}
      </div>
    </div>
    ```

- __Details__: the open/closed state of `details` elements is now preserved when exiting print mode. Prior, details elements were always opened and left open when exiting print mode. Now, they will always return to their prior state.

- __Fonts__: The CSS variables for fonts which are set via `mkdocs.yml` have been renamed, and are amended with fallback fonts by the theme, so they can be set on arbitrary elements. Before, the fallback fonts had to be copied in order to override fonts on a nested element.

### Removed

- ~~__Tabbed (legacy)__~~: from version 8, only the `alternate_style`of the [Tabbed extension](https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/) is supported, and thus mandatory. The alternate implementation is superior in many ways, and there's no reason for us to keep the legacy implementation, as it just blows up the size of the CSS.

- ~~__Disqus__~~: sadly, Disqus free version has become so horrible with advertisements before and after the comment section, which is why I don't want to endorse its usage anymore. Disqus was added at a point in time where its free version was pretty good. This is not the case anymore. However, there's a new `page-footer.html` partial that makes it pretty easy to add it back through customization. The new comment system guide still uses Disqus as an example for a custom integration until we found a new, better provider. Suggestions welcome.

- ~~`extra.manifest`~~: the [web app manifest](https://squidfunk.github.io/mkdocs-material/reference/meta-tags/#adding-a-web-app-manifest) configuration setting was removed because it is essentially just a single `meta` tag that links to a file that must be provided by the author. Use theme extension and add it to `extrahead`.

- ~~`extracopyright`~~: the `extracopyright` variable allows to set a variable via customization that was added after the copyright information. Since the copyright information is now encapsulated in a separate partial, overriding the partial is more flexible. We don't want to provide redundant ways of achieving the same thing.

- ~~`seealso`~~: the `seealso` qualifier was originally adapted from the `readthedocs` theme, in order to make it easier for authors to migrate to Material for MkDocs. However, when the title is omitted, the admonition extension will render it as `Seealso`, which is incorrect English.

- ~~`site_keywords`~~: this was added in a PR and I failed to check if this was actually supported by MkDocs. It isn't. In fact, MkDocs will print a warning that this is an unsupported setting. For this reason, we'll remove it because it only leads to confusion.

- ~~`prebuild_index`~~: previously deprecated, support was now removed. See linked issue (bottom).

### TODO

- [x] Fix positioning issues for code annotations
- [x] Skip empty `p` elements before code annotation list
- [ ] Close code annotation when bubble is clicked again
- [x] Update documentation for Tabbed
- [x] Update documentation for adding back Disqus via customization
- [ ] Update upgrade guide

---

- #3218
- #3145
- #2976
- #2475

**Comment by Andre601** [comment]
Would you be willing to consider implementing native support for other (open-source) discussion systems such as [giscus](https://github.com/giscus/giscus)?

**Comment by facelessuser** [comment]
Ugh, https://github.com/facelessuser/mkdocs-material-extensions breaks with beta versioning 😢. I guess I need to fix that as it makes it hard to test the beta.

```
    M_VER = tuple(int(x) for x in pkg_resources.require('mkdocs-material')[0].version.split('.')[:3])
ValueError: invalid literal for int() with base 10: '0b1'
```

**Comment by facelessuser** [comment]
Never mind, I was on an old local version 🤦🏻

**Comment by facelessuser** [comment]
Testing seems to indicate everything is working as intended (at least for me). Interested in finally playing code annotations now they are coming to the public distribution (never got around to playing with them in insiders 🙃).

**Comment by squidfunk** [comment]
> Would you be willing to consider implementing native support for other (open-source) discussion systems such as giscus?

I'm not sure. I'm thinking of leaving the discussion system implementation as an exercise to the reader. I mean, it's absolutely trivial now that there is `page-footer.html`, but we could definitely switch the documentation to a setup guide for giscus.

**Comment by squidfunk** [comment]
__Update__: I've made some good progress today, but code annotations still suffer from the issues reported in #2475 on mobile. However, since after fixing #3145 we can now place code annotations anywhere in the comment and they're not eaten up, I had some other problems to solve, namely that code annotations are always exactly as wide as the references from which they're generated. I have a working copy, which still needs some polishing, but I'm quite happy with the result. The following screenshot shows that the text after the code annotation lines up perfectly with a non-code-annotation line:

<img width="703" alt="Bildschirmfoto 2021-11-13 um 16 31 50" src="https://user-images.githubusercontent.com/932156/141689273-d1772130-b412-4af8-ab6c-f67845405119.png">

This is a minor, but pretty important detail, because it means that the code is formatted exactly as before.

**Comment by Andre601** [comment]
So, I want to try this out with my docs, because the annotation thing sure could be helpful with the API docs I have.
Question now is, would I need to update anything specific (i.e. pymdownx or the emoji extension) to properly work with this beta build?

**Comment by facelessuser** [comment]
It sounds like only Tabbed should be updated to use new alternate format. That is what I saw from my brief testing.

**Comment by squidfunk** [comment]
Correct, [Tabbed](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tabbed) needs to be set to:

```
markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true 
```

Other than that, if you have customization, some of those might break. I need to find the time to write an upgrade guide, but it's actually not that much for most users, because mostly new partials have been introduced.

**Comment by Andre601** [comment]
I either do something wrong or either Pymdownx's Highlight or Material for MkDocs doesn't support `json5` as a supported syntax for the annotations.
![image](https://user-images.githubusercontent.com/11576465/141819136-cc7e2f56-b3cb-4469-b23a-75c519e08829.png)

Does Material for MkDocs download Pygments or will a manual download be required for it?

**Comment by Andre601** [comment]
> __With the help of my awesome sponsors, I'm happy to announce that the '[Ghost Pepper](https://squidfunk.github.io/mkdocs-material/insiders/#4000-ghost-pepper)' funding goal has been reached, which means that [code annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations), [anchor tracking](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking) and [versioning warnings](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#version-warning) are finding their way into this repository!__
> 
> Since those are some pretty nifty features, it's a good time to wrap them up into a new major release and drop some long-standing deprecated features. This issue will track the progress on the road from the beta to the final release of version 8.
> 
> __If you experience any problems, for now, please report them as a comment in this issue__.
> 
> ## Installation
> 
> ```
> pip install mkdocs-material==8.0.0b1
> ```
> 
> Note that this is a beta release.
> 
> ## Changes
> 
> ### Added
> 
> - [__Code annotations__](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations): this is probably the most anticipated new feature. After finishing the merge and deprecations, I'll revisit the [placement issues on mobile](https://github.com/squidfunk/mkdocs-material/issues/2475). Those need to get fixed before we push out the major release.
> 
> - [__Version warning__](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#version-warning) and [__Anchor tracking__](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking)
> ### Improved
> 
> - __Content partials__: there are now three new partials, which allow customizing the appearance of the Markdown content without overriding `base.html`. This makes it easy to add a further button to the top of a page or to add arbitrary content to the footer of a page:
> 
>     ``` jinja2
>     {% block content %}
>       {% include "partials/page-header.html" %}
>       {% include "partials/page.html" %}
>       {% include "partials/page-footer.html" %}
>     {% endblock %}
>     ```
> 
>     __Update__: this was partially reverted in b4e046787 due to worse build performance and consolidated into a single `content` partial which is not that huge, so there's not much to be copied when customizing. Will be part of the next beta.
>     
> 
> - __Copyright partial__: the copyright has been moved into a separate partial, which lifts the need to override the `footer.html` template when changing the copyright information.
> 
>     ``` jinja2
>     <div class="md-footer-meta md-typeset">
>       <div class="md-footer-meta__inner md-grid">
>         {% include "partials/copyright.html" %}
> 
>         
>         {% if config.extra.social %}
>           {% include "partials/social.html" %}
>         {% endif %}
>       </div>
>     </div>
>     ```
> 
> - __Details__: the open/closed state of `details` elements is now preserved when exiting print mode. Prior, details elements were always opened and left open when exiting print mode. Now, they will always return to their prior state.
> 
> - __Fonts__: The CSS variables for fonts which are set via `mkdocs.yml` have been renamed, and are amended with fallback fonts by the theme, so they can be set on arbitrary elements. Before, the fallback fonts had to be copied in order to override fonts on a nested element.
> 
> ### Removed
> 
> - ~~__Tabbed (legacy)__~~: from version 8, only the `alternate_style`of the [Tabbed extension](https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/) is supported, and thus mandatory. The alternate implementation is superior in many ways, and there's no reason for us to keep the legacy implementation, as it just blows up the size of the CSS.
> 
> - ~~__Disqus__~~: sadly, Disqus free version has become so horrible with advertisements before and after the comment section, which is why I don't want to endorse its usage anymore. Disqus was added at a point in time where its free version was pretty good. This is not the case anymore. However, there's a new `page-footer.html` partial that makes it pretty easy to add it back through customization. The new comment system guide still uses Disqus as an example for a custom integration until we found a new, better provider. Suggestions welcome.
> 
> - ~~`extra.manifest`~~: the [web app manifest](https://squidfunk.github.io/mkdocs-material/reference/meta-tags/#adding-a-web-app-manifest) configuration setting was removed because it is essentially just a single `meta` tag that links to a file that must be provided by the author. Use theme extension and add it to `extrahead`.
> 
> - ~~`extracopyright`~~: the `extracopyright` variable allows to set a variable via customization that was added after the copyright information. Since the copyright information is now encapsulated in a separate partial, overriding the partial is more flexible. We don't want to provide redundant ways of achieving the same thing.
> 
> - ~~`seealso`~~: the `seealso` qualifier was originally adapted from the `readthedocs` theme, in order to make it easier for authors to migrate to Material for MkDocs. However, when the title is omitted, the admonition extension will render it as `Seealso`, which is incorrect English.
> 
> - ~~`site_keywords`~~: this was added in a PR and I failed to check if this was actually supported by MkDocs. It isn't. In fact, MkDocs will print a warning that this is an unsupported setting. For this reason, we'll remove it because it only leads to confusion.
> 
> - ~~`prebuild_index`~~: previously deprecated, support was now removed. See linked issue (bottom).
> 
> ### TODO
> 
> - [ ] Fix positioning issues for code annotations
> - [x] Update documentation for Tabbed
> - [x] Update documentation for adding back Disqus via customization
> - [ ] Update upgrade guide
> 
> ---
> 
> - #3218
> - #3145
> - #2976
> - #2475

Well... json5 is a thing... It is exactly for the purpose of having comments... Just test it with GitHub and you'll see

**Comment by Andre601** [comment]
> So first, there doesn't seem to be a [JSON5](https://github.com/pygments/pygments/issues/1880) lexer. Second, JSON doesn't support comments. For now, you can use the `js` lexer, which looks almost the same as JSON and supports both `// ...`and `/* ... */` comments. Pygments syntax highlighting is required. This is also mentioned in the [documentation](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations).
> 
> In the future, there will be an alternate syntax to add code annotations to any line, regardless of language. The limitation will be that they can only be added at the end, which should however work for most use cases.
> 
> > Does Material for MkDocs download Pygments or will a manual download be required for it?
> 
> Pygments is automatically installed and enabled when you use `pymdownx.highlight`, unless explicitly disabled.

Json5 is a thing... It is precisely for comment support.

Example:
```json5
{
  "som_json": "with comments" // See?
}
```

**Comment by facelessuser** [comment]
`pymdownx.highlight` just uses whatever Pygments provides and whatever 3rd party Pygment's lexers you've installed. I'm sure you could probably subclass the JSON lexer and create a JSON5 version. I realize it isn't trivial though. Personally, using JS is usually sufficient.

**Comment by corykinney** [comment]
Not sure if this deserves its own issue, since I don't remember it happening before the beta for version 8 started, but the mermaid.js diagram examples are showing up as normal code blocks on the [documentation page](https://squidfunk.github.io/mkdocs-material/reference/diagrams/) for me. 

On a different note, and this is just a personal opinion, I think it might be more intuitive if code annotation bubbles acted as a toggle, where you could click to open and click to close, rather than having to click elsewhere on the page (although I think that should remain).

**Comment by squidfunk** [comment]
Mermaid integration is still [exclusively in Insiders](https://squidfunk.github.io/mkdocs-material/insiders/#5000-aji-panca) 😉 It will be released here when the next funding goal is hit.

**Comment by corykinney** [comment]
> Mermaid integration is still [exclusively in Insiders](https://squidfunk.github.io/mkdocs-material/insiders/#5000-aji-panca) 😉 It will be released here when the next funding goal is hit.

Yes, and I am looking forward to that so I can use it! But when I visit your live documentation, for each diagram type, it has an **Example** block and a **Result** block. Isn't the **Result** supposed to show the actual diagram that would be rendered?

**Comment by squidfunk** [comment]
Ah, interesting! Yes, that's definitely an error, but it's not related to version 8. I'll look into that.

**Comment by Andre601** [comment]
> So first, there doesn't seem to be a [JSON5](https://github.com/pygments/pygments/issues/1880) lexer. Second, JSON doesn't support comments. For now, you can use the `js` lexer, which looks almost the same as JSON and supports both `// ...`and `/* ... */` comments. Pygments syntax highlighting is required. This is also mentioned in the [documentation](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations).
> 
> In the future, there will be an alternate syntax to add code annotations to any line, regardless of language. The limitation will be that they can only be added at the end, which should however work for most use cases.
> 
> > Does Material for MkDocs download Pygments or will a manual download be required for it?
> 
> Pygments is automatically installed and enabled when you use `pymdownx.highlight`, unless explicitly disabled.

Sadly doesn't work...
The highlighting works, but the annotations aren't recognized or rendered... Could it be because I set a custom title?

![image](https://user-images.githubusercontent.com/11576465/141845903-5c8ffc4a-9cba-4da5-b620-64ed1f44b6a3.png)

**Comment by squidfunk** [comment]
@corykinney fixed, that was just stale configuration!

**Comment by squidfunk** [comment]
@Andre601 no, it should work despite the custom title. Could you provide the Markdown please? Also, did you enable the `content.code.annotate` feature flag?

**Comment by Andre601** [comment]
> @Andre601 no, it should work despite the custom title. Could you provide the Markdown please? Also, did you enable the `content.code.annotate` feature flag?

Here's a gist of the file: https://gist.github.com/Andre601/df9bbd4cf35247cee7cd051aff6414c9
And yes, the feature flag is enabled. You can find current configuration on this repo's branch: https://github.com/purrbot-site/Docs/tree/feature/use-material-v8

**Comment by squidfunk** [comment]
The indentation is incorrect – the list is outside of the tab, you must indent the list so that it matches the code block indent. Your list is currently not coming next, after the code block, but after the tab.

**Comment by Andre601** [comment]
> The indentation is incorrect – the list is outside of the tab, you must indent the list so that it matches the code block indent. Your list is currently not coming next, after the code block, but after the tab. This:
> 
> ```
> === "Body"
>     ```js title="JSON Body Example"
>     ...
>     ```
> 
> 1.  Foo
> ```
> 
> Must be:
> 
> ```
> === "Body"
>     ```js title="JSON Body Example"
>     ...
>     ```
> 
>     1.  Foo
> ```

....that's a typical andre moment... 🤦

**Comment by Andre601** [comment]
One other question.

Will later sections require a continued nummeration or could I repeat 1, 2, etc.?

Like would it need to be:
````
```js
{
  "text": "text" // (1)
```

1.  Text

```js
{
  "text": "text" // (2)
```

2.  More text
````
or would this work?
````
```js
{
  "text": "text" // (1)
```

1.  Text

```js
{
  "text": "text" // (1)
```

1.  More text
````
I'm not sure since the docs only use one text example which doesn't make it clear...

**Comment by squidfunk** [comment]
The numbers are per-code block. The reason for this is that Markdown lists will always restart, so even though you may number your Markdown list 4., 5., 6., it will be converted to `li` elements which are implicitly numbers through CSS. Thus, the only options is to always start again.

**Comment by Andre601** [comment]
Encountering the same issue with annotations not rendering again...
This time are the lists in the right indeed, but I assume the issue is multiple tabs(?)

Markdown:
```markdown
### /api/quote { #error-api-quote }

=== "Empty JSON Body/No JSON"
    **Status-Code**: [400]  
    ```js
    {
      "details": {
        "path": "/api/quote", // (1)
        "content-type": ":content-type", // (2)
        "user-agent": ":user-agent" // (3)
      },
      "error": true,
      "message": "Received invalid or empty JSON Body."
    }
    ```
    
    1.  The Path you accessed. This should be `/api/quote` for this endoint.
    2.  The content-tyoe you provided. This **must** be `application/json`.
    3.  The User-Agent you used.

=== "Malformed JSON/Invalid Values"
    **Status-Code**: [500]  
    ```js
    {
      "details": {
        "path": "/api/quote", // (1)
        "content-type": ":content-type", // (2)
        "user-agent": ":user-agent" // (3)
      },
      "error": true,
      "message": "Couldn't generate Image. Make sure the values are valid!"
    }
    ```
    
    1.  The Path you accessed. This should be `/api/quote` for this endoint.
    2.  The content-tyoe you provided. This **must** be `application/json`.
    3.  The User-Agent you used.
```

**Comment by squidfunk** [comment]
Confirmed. The Markdown parser inserts an empty `p` tag between the code block and list element:

``` html
<div class="tabbed-block">
  <p>...</p>
  <div class="highlight">...</div>
  <p></p>
  <ol>...</ol>
</div>
```

However, when I add a newline before the code block (After the **Status Code** section**), the `p` element is gone. @facelessuser do you have any idea if this is a Markdown parsing quirk or a potential bug?

<img width="602" alt="Bildschirmfoto 2021-11-16 um 07 49 58" src="https://user-images.githubusercontent.com/932156/141935451-267baecf-7c27-4114-87ac-d8325ae76d66.png">

**Comment by squidfunk** [comment]
Thanks for the explanation, @facelessuser

> Can you see the issue yet? <div> is a block element and is not allowed in <p> and will be treated as a block. That causes the browser to cause a real break and then resolve the opening <p> and the closing </p> as separate paragraphs:

Whoa, you're absolutely right. This is exactly what the parser generates (I just inspected the HTML) and the browser corrects. HTML5, ay. I guess we should just expect this quirk to happen from time to time, which is why I'll add handling for this case to the code annotation code.

**Comment by facelessuser** [comment]
Sure, if it eases asking this question, I can see maybe just handling it. I would strongly encourage people to treat code blocks as separate blocks with new lines to separate them from other content, but it sure doesn't hurt if code annotations can detect and handle this scenario as well 🙂.

**Comment by Andre601** [comment]
I for now applied that fix and the docs work fine. Had to update the partials and stuff because footer was no longer correctly overridden, but everything works now like it should for me.

**Comment by ThuF** [comment]
Hi @squidfunk,

After upgrading from **7.3.6** to **8.0.0b1** the following issue appears:

![xsk-setup-doc-issue](https://user-images.githubusercontent.com/4092083/142011859-cc3bb39d-6b01-485b-8923-61c8bce10985.png)

While with the previous version it was working fine:
![xsk-setup-doc-expected](https://user-images.githubusercontent.com/4092083/142011952-05726947-7456-4d87-beff-7b3e12663730.png)

The page could be found here: https://www.xsk.io/setup/
The source could be found here: https://github.com/SAP/xsk/blob/gh-pages/docs-site/docs/setup/index.md?plain=1#L19-L127

Regards,
Yordan

**Comment by squidfunk** [comment]
Thanks for reporting – you need to adjust the configuration, see https://github.com/squidfunk/mkdocs-material/issues/3219#issuecomment-969058456

**Comment by squidfunk** [comment]
> I for now applied that fix and the docs work fine. Had to update the partials and stuff because footer was no longer correctly overridden, but everything works now like it should for me.

Perfect! I hope to find some time in the next days to write the upgrade guide with step-by-step upgrade instructions. The footer partial was changed as noted in the OP, but the changes should be quite easy to integrate.

**Comment by NicolasMassart** [comment]
Hi @squidfunk ! First congrats, this new version seems awesome, I was able to test it very quickly without too much to change (just some overrides and config, but not much and very easy diff) to make it compatible with my existing setup.

I also tried the new code annotation feature and it works well.
I still have one question:
how to add annotation in a Markdown code block? what is the expected comment syntax?

**Comment by squidfunk** [comment]
> how to add annotation in a Markdown code block? what is the expected comment syntax?

That's a good question. It seems that the Markdown lexer doesn't detect HTML comments:

```` markdown
``` markdown
I'm **Markdown** <!-- (1) -->
```

1. This doesn't work
````

However, there's an [alternate Markdown lexer](https://github.com/jhermann/pygments-markdown-lexer/blob/master/src/pygments_markdown_lexer/lexer.py) that may have support. I have some ideas how to build a solution that does not require Pygments parsing or the presence of comments at a later point. First, I want to get code annotations stable 😊

**Comment by NicolasMassart** [comment]
Yes I tried html comment as well as the intelliJ Markdown comment format `[//]: # (&#40;1&#41;)` (the IDE does something strange when you hit `cmd + /` ) and none of them work.

**Comment by johnthagen** [comment]
Just an idea, but would it be possible to make it so that when you press the "Copy to clipboard" button for a code block that used annotations that the `# ` before the annotation wasn't copied?

The new annotations look great, but it seems like a downside is they clutter copied commands (e.g. when using with `bash` highlighting) with extra comment characters.

Consider a `bash` block like:

```bash
command \
   --argument1 \ # (1)
   --argument2 \
```

When the user copies this, the second `\` won't be used properly when its pasted into a terminal.

**Comment by squidfunk** [comment]
@johnthagen the problem is that it's not really decidable what of a comment should be copied and what not, e.g.:

``` js
const foo // this is a (1) comment
```

I think it's better to replace annotations with their textual counter part, e.g. `(1)` when copying, so it's consistent.

**Comment by johnthagen** [comment]
> I'm thinking of an alternate syntax that allows to revert back to the old behavior, stripping the entire block.

That sounds great to me.

**Comment by Wen-Tao-Zhang** [comment]
Many thanks to all contributors for your great efforts!

Everything turns out great. Just want to share my strugglling during the past hour: I'm not sure whether I will be the only silly, poor guy to do so. :rofl:

I recoganized the important `- content.code.annotate` configuration snippet as _just_ a demonstration of whatever code, since itself uses code annotation. So I skipped it every time as I read through the documentation trying to figure out why my annotation was not working.

**Comment by squidfunk** [comment]
@Wen-Tao-Zhang hmm, the [documentation](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations) states that it must be enabled in `mkdocs.yml`, doesn't it? Excerpt:

> Code annotations offer a comfortable and friendly way to attach arbitrary content to specific sections of code blocks by adding numeric markers in block and inline comments in the language of the code block. __Add the following to `mkdocs.yml` to enable them globally:__

Any idea how we could further improve this?

**Comment by Wen-Tao-Zhang** [comment]
> Any idea how we could further improve this?

I was not suggesting that. The documentation is good. I just somehow got stuck because I skim through the documentation over and over _carelessly_. My post was just a reminder for someone like me (if there's any) :rofl:.

Thank you for your quick reply!

**Comment by corykinney** [comment]
> I'd be interested to hear other user's opinions on this. Personally I find it pretty intuitive, but I'm willing to discuss.

Late response, but just wanted to clarify that I wasn't suggesting removing clicking outside of the annotation to close it, but that clicking the bubble should **also** close the annotation.

**Comment by julienlavergne** [comment]
> Just an idea, but would it be possible to make it so that when you press the "Copy to clipboard" button for a code block that used annotations that the `# ` before the annotation wasn't copied?
> 
> The new annotations look great, but it seems like a downside is they clutter copied commands (e.g. when using with `bash` highlighting) with extra comment characters.
> 
> Consider a `bash` block like:
> 
> ```shell
> command \
>    --argument1 \ # (1)
>    --argument2 \
> ```
> 
> When the user copies this, the second `\` won't be used properly when its pasted into a terminal.

Also interested in this. It would be consistent with other features that "augment" the block without having to touch the content, like syntax coloring and line highlight.

And it would also open the door in having annotation working with snippets and overall block that do not easily supports comments.

**Comment by ofek** [comment]
Great work 💯 

FYI, we are also extremely interested in code annotations not interfering with copying.

**Comment by Wen-Tao-Zhang** [comment]
> Consider a `bash` block like:
> 
> ```shell
> command \
>    --argument1 \ # (1)
>    --argument2 \
> ```
> 
> When the user copies this, the second `\` won't be used properly when its pasted into a terminal.

FWIW, I recently came across a [page](https://www.jenkins.io/doc/book/installing/docker/#on-macos-and-linux) (and its [source](https://github.com/jenkins-infra/jenkins.io/blob/master/content/doc/book/installing/_docker.adoc?plain=1#L32-L44)) with code blocks like this, who seems to use AsciiDoc. Not sure how/whether they handle the issue mentioned [here](https://github.com/squidfunk/mkdocs-material/issues/3219#issuecomment-971769355) by the author.

**Comment by squidfunk** [comment]
> FYI, we are also extremely interested in code annotations not interfering with copying.

@ofek Thanks for the feedback! Code annotations do not interfere with copying – they are not marked with `user-select: none`, so the actual content is not included. They are also stripped when using the copy-to-clipboard button. However, the comment where they are placed is, so I guess you're seconding this idea?

**Comment by squidfunk** [comment]
__I'm very grateful for the feedback!__ Just to be clear what the rationale behind the current implementation is:

> It would be consistent with other features that "augment" the block without having to touch the content, like syntax coloring and line highlight.

This is in fact exactly what code annotations do – they just replace markers in *comments* – nothing more. This means that a valid code snippet will remain valid, but invalid code snippets are *not corrected to be valid*. Let's take the example that was posted earlier again:

``` sh
command \
   --argument1 \ # (1)
   --argument2 \
```

This example is invalid, because *comments are not allowed in this position*. This means that it's (currently) not possible to add a code annotation on this line, same as it's not possible to add a comment in the underlying language. So yes, we could add an alternate syntax that says "strip the entire comment and inline the annotation", but this means that the code example would render as invalid code in the following cases:

1. **JavaScript is not available**: slow connections, JavaScript turned off, whatever – code annotations will currently gracefully fallback to a Markdown block with your original comments, i.e. `(1)`, `(2)`, + a list below it. This was a deliberate decision because it's a design principle that Material for MkDocs follows – always work without JavaScript, if possible. Of course, features as search are not possible to implement without JavaScript, but the site is perfectly usable without JavaScript.

2. **Printing annotations**: printing annotations is basically the same as "no JavaScript", because now code annotations are shown in their original form – a list below a Markdown block because that's the only way to support non-interactive mediums. Again, the code block would be invalid.

Nonetheless, I'm considering adding the stripping mode, but I have to work out the details for that. I want to revisit this topic together with placing annotations in languages that don't support comments because both problems are closely related. This is, however, something that can't be part of the 8.x release, because it's a whole other rabbit hole to go down. For this reason, please understand that code annotations are currently only valid in comments, which is stated in the documentation.

**Comment by squidfunk** [comment]
__8.0.0b2 is out!__ This was really tough. [Release notes](https://github.com/squidfunk/mkdocs-material/releases/tag/8.0.0b2):

- Switched to `:is()` selector for simple selector lists (main.css drops from 18kb to 16kb gzipped)
- Switched autoprefixer from _last 4 years_ to _last 2 years_
- Fixed code annotations not scrolling on overflowing code blocks
- Fixed code annotations rendered too narrow on mobile
- Fixed code annotations overflowing on mobile
- Fixed code after code annotations not aligning with grid

Again, feedback appreciated. The current iteration plan is to fix some outstanding issues and do some refactoring in the coming weeks, and then push out a final RC. I'm sorry that the way to a stable release is a little longer this time, but it will be worth it. Smaller footprint, some long overdue refactorings, and awesome new features.

**Comment by timvink** [comment]
Excited about this one!

Would `v8` also be the right release to deprecate `source-date.html` partial, in favor of `source-file.html` ? See https://github.com/squidfunk/mkdocs-material/blob/409d1510440b3d1488a33213f12049a985161313/src/partials/source-date.html#L23-L24 

I'd need to fix a plugin as well (https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/53)

**Comment by squidfunk** [comment]
Yep, I've already removed the partial and everything that was linked to it.

**Comment by jrappen** [comment]
@squidfunk You might want to mention the new copyright partial on the [setting up the footer page](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#copyright-notice).

**Comment by squidfunk** [comment]
I've finished work on the v8 branch and just merged it into `master`. I'll add the missing pieces to the documentation and will issue a release. Many thanks to all who took part in the beta. Since there was now much feedback on the betas, I decided to skip the RCs and just get it out the door.

**Comment by squidfunk** [comment]
8.0.0 was just released. Please report any issues encountered as usual (and not here).

**Comment by Andre601** [comment]
Nice work.

One thing tho: Looking at the [Adding a comment system]() page, do I feel like it kinda favours Disqus a bit too much and goes more into "How to setup Disqus" rather than "How to setup any Javascript-based comment system".

I feel like the page should be made a bit more generic and at most mention stuff you have to add alongside the basics to support Disqus.

Like from my basic JS knowledge and stuff do solutions like Giscuss not need that first time setup to function.

I can offer to try and redo the page a bit, but currently thinking what the best wording would be to do this...

**Comment by squidfunk** [comment]
I already said in another comment that I'm happy to switch to another comment system provider or provide docs for multiple providers. Happy to collaborate on a PR, as from my viewpoint this is not a priority. Any help is appreciated.

Note that the generic part boils down to "extend the template and add what the provider gave you".

**Comment by squidfunk** [comment]
Oh, an @corykinney – thanks for the idea for closing open annotations on a subsequent click on the index. This is also included in the latest release. It's really a great idea.

**Comment by corykinney** [comment]
@squidfunk of course! Thanks for implementing it and offering so many awesome features in the free version!

**Comment by squidfunk** [comment]
As wished in https://github.com/squidfunk/mkdocs-material/issues/3219#issuecomment-971736192, the latest commit on the Insiders repository adds the ability to add an `!` to a code annotation, which will replace the entire comment, stripping any control characters. This is the first extension towards code annotations in languages that don't support comments. More is about to come.

__Markdown__

```` markdown
``` sh
pip install \
  mkdocs-material \
  mkdocs-awesome-pages-plugin \ # (1)!
  ...
```

1. Complete replacement
````

__ Result__

<img width="461" alt="Bildschirmfoto 2021-12-09 um 22 12 10" src="https://user-images.githubusercontent.com/932156/145476665-1e9c4ad1-3f0d-4697-a800-83386285b97a.png">



I'll wrap this up, add documentation and tie it to a funding goal when it will be released.

**Comment by squidfunk** [comment]
The changes were released as part of __8.1.0+insiders-4.4.0__, which also adds the ability to directly link to code annotations. See a demo here: https://twitter.com/squidfunk/status/1469245481255673857
