### ISSUE TITLE
Meta title should override page title in tag indexes

### ISSUE THREAD

**Issue by ehguille** [squidfunk/mkdocs-material#3506]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

When creating an index containing the meta tags, the generated page shows the page title, not the meta title.

### Use Cases

When a tag appears in two different pages, you can't tell which one are refering.

### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/55703981/151525231-abc5638c-0f4a-4734-887c-511d63f3ba26.png)

**Comment by squidfunk** [comment]
Fixed in [`9b0c02386`](https://github.com/squidfunk/mkdocs-material-insiders/commit/9b0c023867cdbf81e9eb2747a8f4aeaa70102f09) 😊

**Comment by squidfunk** [comment]
Released as part of 8.1.9+insiders-4.7.1.
