### ISSUE TITLE
Emitting a custom event for anchor tracking

### ISSUE THREAD

**Issue by heitorlessa** [squidfunk/mkdocs-material#3537]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I'm enabling [Anchor Tracking](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking) as part of the migration to MKdocs Material 8.x. This feature can help give a more accurate analytics on which sections are more popular than other - however, I've just noticed it's [rewriting the history state](https://github.com/squidfunk/mkdocs-material/blob/14a89bc9ea7c0187fba55a75c66a958f25500cdc/src/assets/javascripts/components/toc/index.ts#L293).

With my limited research on history rewriting, I can't hook up to any event (e.g. `popState`) to send a custom anonymous page view for that section being tracked.

Would you consider creating a [custom event](https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events) so we can use this great feature for analytics purpose too?

Thank you as always for this great theme!!

### Use Cases

Use the new anchor tracking feature to send more accurate page view for sections being scrolled to.

**Comment by squidfunk** [comment]
Moving to discussion, since this is a customization request.
