### ISSUE TITLE
navigation.instant should refresh custom meta tags

### ISSUE THREAD

**Issue by vedranmiletic** [squidfunk/mkdocs-material#3561]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

[My group website](https://group.miletic.net/) advertises a .onion (Tor) address via a http-equiv meta tag, which includes the .onion domain name and a path. This tag is expectedly not refreshed when loading another page with `navigation.instant` enabled. It would be nice if all meta tags would be refreshed, even those added by the user via overrides.

### Use Cases

Users put all kinds of meta tags (the actual tags used vary from site to site) that are different from one page to another, e.g. og:url and og:title properties. It would be great if these were refreshed along with the page title, description, and author, regardless of the tags used.

**Comment by squidfunk** [comment]
Thanks for suggesting. I've investigated whether we can add general support for refreshing all metadata in the `head`, but unfortunately, it's an almost undecidable problem _what_ to refresh. The challenge is to determine the bidirectional mapping of metadata between both documents, i.e. which tags to add/keep/replace. Some background:

The naive approach would be to just replace the entire content of `head`, which is not feasible as instant loading would begin to flash with unstyled content, as we would remove all styles, then add them back. We _must_ keep the already evaluated scripts and styles, and possibly other stuff. Thus, I'd consider this approach a dead end. It's in fact the very reason I've decided to refresh selected tags and components only.

We could also try to determine what to refresh, but I suspect that this approach would be so fragile given that authors add custom metadata and other stuff to the `head` which will then break in unexpected ways. I'm not sure I'd want to maintain this since it'll be an uphill battle keeping this running.

However, I suspect that your use case ...

> Users put all kinds of meta tags (the actual tags used vary from site to site) that are different from one page to another, e.g. og:url and og:title properties. It would be great if these were refreshed along with the page title, description, and author, regardless of the tags used.

... does not suffer from this problem at all, as `og:*` metadata is usually loaded in one go by social sites, and not after navigating the site. Thus, I'm not considering implementing this right now. If you still need to replace metadata, you can do so by leveraging the `document$` observable. This way, you can deliberately decide what to replace:

``` js
document$.subscribe(replacement => {
  /* Only for demonstration, you can replace anything you need */
  document.title = replacement.title
})
```

**Comment by vedranmiletic** [comment]
Thanks for the investigation. I am aware this is far from a trivial endeavour.

Just a slight correction, `og:` tags are nice and I use them, but not that much. My use case for this is `meta http-equiv="onion-location"`. Would it be be feasible to add a rule to replace all `http-equiv` meta tags indiscriminately, if present?

**Comment by squidfunk** [comment]
Since this tag is something you customized, I'd kindly ask you to use the JavaScript I provided in my last comment to add the logic yourself. I can't add more and more exceptions for things that are customized. Instant loading will only replace the tags that can be _configured_, not customized. Otherwise we'll be adding the next and the next and the next tag 😉

**Comment by vedranmiletic** [comment]
Thanks for the suggestion, I will look into doing it like that.
