### ISSUE TITLE
description property not converted to meta tag

### ISSUE THREAD

**Issue by tbswork1** [squidfunk/mkdocs-material#4312]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

We have something like below on each of the md files,

`---
Description: Summarizes organization of ....
Keywords: xxxx
title: Object Overview
---
`
but the meta description tag is missing in generated html files. 

### Expected behaviour

The `Description` and `Keyword` properties automatically converted to description and keywords meta tags in html.

### Actual behaviour

description and keywords meta tags missing in html.

### Steps to reproduce

mkdocs serve

### Package versions

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`
Python 3.9.13
mkdocs, version 1.3.1
Material: latest

### Configuration

```yaml
site_name: User Manual
use_directory_urls: false
site_url: https://url
```

### System information

- Operating system: Windows
- Browser: any

**Comment by squidfunk** [comment]
Thanks for reporting. If you set a [page description](https://squidfunk.github.io/mkdocs-material/reference/#setting-the-page-description), the `meta` description tag is set:

https://github.com/squidfunk/mkdocs-material/blob/909591e0a8fa87c27db8989be3eaec15edf1d2b2/src/base.html#L34-L39

The `keywords` meta tag was removed some time ago, as it doesn't provide any value, see #880.

**Comment by tbswork1** [comment]
I found the problem that pandoc, which generates the md files, places the description property as 'Description', not 'description'. mkdocs treats it as case-sensitive. Thus, it is ignored.

**Comment by squidfunk** [comment]
I see. In the MkDocs ecosystem, I haven't seen any front matter being titlecase – lowercase is the norm. Thus you might need to convert the properties to lowercase before feeding them to MkDocs.
