### ISSUE TITLE
More colors for task list

### ISSUE THREAD

**Issue by TristisOris** [squidfunk/mkdocs-material#5593]
### Description

Would be nice to get red and yellow colors.

### Related links

[- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-](https://squidfunk.github.io/mkdocs-material/reference/lists/?h=list#using-task-lists)https://squidfunk.github.io/mkdocs-material/reference/lists/?h=list#using-task-lists

### Use Cases

Simple task tracker - up to date, need update, outdated.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.
