### ISSUE TITLE
Meta and other plugins no longer appear to be built-in

### ISSUE THREAD

**Issue by discdiver** [squidfunk/mkdocs-material#5695]
### Context

New error 

Docs built fine last week, now the `meta` plugin doesn't appear to be built in any longer.

[The docs](https://squidfunk.github.io/mkdocs-material/reference/?h=plugins+met#built-in-meta-plugin) say:

>  The built-in meta plugin allows to set front matter per folder, which is especially handy to ensure that all pages in a folder use specific templates or tags. Add the following lines to mkdocs.yml:

### Bug description

Error when using the meta plugin:

```
ERROR    -  Config value 'plugins': The "meta" plugin is not installed
Aborted with 1 Configuration Errors!
```

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [The docs](https://squidfunk.github.io/mkdocs-material/reference/?h=plugins+met#built-in-meta-plugin) say:

>  The built-in meta plugin allows to set front matter per folder, which is especially handy to ensure that all pages in a folder use specific templates or tags. Add the following lines to mkdocs.yml:

### Reproduction

Install the latest insiders build.

In mkdocs.insiders.yml 

```
INHERIT: mkdocs.yml
plugins:
    meta:
```

### Steps to reproduce

Install the latest insiders build.

In mkdocs.insiders.yml 

```
INHERIT: mkdocs.yml
plugins:
    meta:
```

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [ ] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by discdiver** [comment]
I'm not able to create a .zip because the build fails. I followed the steps in the reproduction and this is my mkdocs.yml file:

```
site_name: My Docs

theme:
  name: material
plugins:
  meta:
  info:
  ```

Traceback:
```
ERROR    -  Config value
            'plugins': The "meta"
            plugin is not
            installed
Aborted with 1 Configuration Errors!
```

**Comment by discdiver** [comment]
Upon further evaluation, it looks like this is an issue for other plugins including privacy, social, and typeset.

**Comment by ossinova** [comment]
Same goes for thee built in blog plugin

**Comment by squidfunk** [comment]
I'm not able to reproduce this problem. Here's what I did:

```
squidfunk@squidfunk2020 /tmp $ mkdir mkdocs-test                       
squidfunk@squidfunk2020 /tmp $ cd mkdocs-test    
squidfunk@squidfunk2020 /tmp/mkdocs-test $ virtualenv venv
/usr/local/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
created virtual environment CPython3.8.14.final.0-64 in 432ms
  creator CPython3Posix(dest=/private/tmp/mkdocs-test/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/squidfunk/Library/Application Support/virtualenv)
    added seed packages: pip==23.1.2, setuptools==67.8.0, wheel==0.40.0
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
squidfunk@squidfunk2020 /tmp/mkdocs-test $ . ./venv/bin/activate
(venv) squidfunk@squidfunk2020 /tmp/mkdocs-test $ pip install pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git

(venv) squidfunk@squidfunk2020 /tmp/mkdocs-test $ pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git            

Collecting git+https://github.com/squidfunk/mkdocs-material-insiders.git
  Cloning https://github.com/squidfunk/mkdocs-material-insiders.git to /private/var/folders/8z/8l6rfv895bgbst1hfmc19khh0000gn/T/pip-req-build-g3dw1ins
  Running command git clone --filter=blob:none --quiet https://github.com/squidfunk/mkdocs-material-insiders.git /private/var/folders/8z/8l6rfv895bgbst1hfmc19khh0000gn/T/pip-req-build-g3dw1ins
  Resolved https://github.com/squidfunk/mkdocs-material-insiders.git to commit fe2d494410df15d6b9edbd58bac068de1529654b
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting babel>=2.10.3 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached Babel-2.12.1-py3-none-any.whl (10.1 MB)
Collecting colorama>=0.4 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting jinja2>=3.0 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting lxml>=4.6 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached lxml-4.9.3-cp38-cp38-macosx_10_15_x86_64.whl
Collecting markdown>=3.2 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached Markdown-3.4.3-py3-none-any.whl (93 kB)
Collecting mkdocs-material-extensions>=1.1 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached mkdocs_material_extensions-1.1.1-py3-none-any.whl (7.9 kB)
Collecting mkdocs>=1.4.2 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached mkdocs-1.4.3-py3-none-any.whl (3.7 MB)
Collecting paginate>=0.5.6 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached paginate-0.5.6-py3-none-any.whl
Collecting pipdeptree>=2.3 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Downloading pipdeptree-2.9.4-py3-none-any.whl (18 kB)
Collecting pygments>=2.14 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached Pygments-2.15.1-py3-none-any.whl (1.1 MB)
Collecting pymdown-extensions>=9.9.1 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached pymdown_extensions-10.0.1-py3-none-any.whl (240 kB)
Collecting readtime>=2.0 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached readtime-2.0.0-py3-none-any.whl (7.6 kB)
Collecting regex>=2022.4.24 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached regex-2023.6.3-cp38-cp38-macosx_10_9_x86_64.whl (294 kB)
Collecting requests>=2.26 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting pytz>=2015.7 (from babel>=2.10.3->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting MarkupSafe>=2.0 (from jinja2>=3.0->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached MarkupSafe-2.1.3-cp38-cp38-macosx_10_9_x86_64.whl (13 kB)
Collecting importlib-metadata>=4.4 (from markdown>=3.2->mkdocs-material==9.1.18+insiders.4.37.0)
  Downloading importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
Collecting click>=7.0 (from mkdocs>=1.4.2->mkdocs-material==9.1.18+insiders.4.37.0)
  Downloading click-8.1.4-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 kB 346.2 kB/s eta 0:00:00
Collecting ghp-import>=1.0 (from mkdocs>=1.4.2->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached ghp_import-2.1.0-py3-none-any.whl (11 kB)
Collecting markdown>=3.2 (from mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached Markdown-3.3.7-py3-none-any.whl (97 kB)
Collecting mergedeep>=1.3.4 (from mkdocs>=1.4.2->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached mergedeep-1.3.4-py3-none-any.whl (6.4 kB)
Collecting packaging>=20.5 (from mkdocs>=1.4.2->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting pyyaml-env-tag>=0.1 (from mkdocs>=1.4.2->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached pyyaml_env_tag-0.1-py3-none-any.whl (3.9 kB)
Collecting pyyaml>=5.1 (from mkdocs>=1.4.2->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached PyYAML-6.0-cp38-cp38-macosx_10_9_x86_64.whl (192 kB)
Collecting watchdog>=2.0 (from mkdocs>=1.4.2->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached watchdog-3.0.0-cp38-cp38-macosx_10_9_x86_64.whl (91 kB)
Collecting beautifulsoup4>=4.0.1 (from readtime>=2.0->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting markdown2>=2.4.3 (from readtime>=2.0->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached markdown2-2.4.9-py2.py3-none-any.whl (39 kB)
Collecting pyquery>=1.2 (from readtime>=2.0->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached pyquery-2.0.0-py3-none-any.whl (22 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.26->mkdocs-material==9.1.18+insiders.4.37.0)
  Downloading charset_normalizer-3.2.0-cp38-cp38-macosx_10_9_x86_64.whl (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.8/124.8 kB 416.3 kB/s eta 0:00:00
Collecting idna<4,>=2.5 (from requests>=2.26->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.26->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached urllib3-2.0.3-py3-none-any.whl (123 kB)
Collecting certifi>=2017.4.17 (from requests>=2.26->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting soupsieve>1.2 (from beautifulsoup4>=4.0.1->readtime>=2.0->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached soupsieve-2.4.1-py3-none-any.whl (36 kB)
Collecting python-dateutil>=2.8.1 (from ghp-import>=1.0->mkdocs>=1.4.2->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting zipp>=0.5 (from importlib-metadata>=4.4->markdown>=3.2->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting cssselect>=1.2.0 (from pyquery>=1.2->readtime>=2.0->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached cssselect-1.2.0-py2.py3-none-any.whl (18 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.1->ghp-import>=1.0->mkdocs>=1.4.2->mkdocs-material==9.1.18+insiders.4.37.0)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: mkdocs-material
  Building wheel for mkdocs-material (pyproject.toml) ... done
  Created wheel for mkdocs-material: filename=mkdocs_material-9.1.18+insiders.4.37.0-py3-none-any.whl size=19344403 sha256=ff9e93db95b3b546a0702fc8b9b861e8db1f2e3cae123c6163b4bb8850e03ea1
  Stored in directory: /private/var/folders/8z/8l6rfv895bgbst1hfmc19khh0000gn/T/pip-ephem-wheel-cache-b2limq2k/wheels/8d/53/66/020d2905e81d798bf7f10d005dd01f80ada66d3c7e51e0501d
Successfully built mkdocs-material
Installing collected packages: pytz, paginate, zipp, watchdog, urllib3, soupsieve, six, regex, pyyaml, pygments, pipdeptree, packaging, mkdocs-material-extensions, mergedeep, MarkupSafe, markdown2, lxml, idna, cssselect, colorama, click, charset-normalizer, certifi, babel, requests, pyyaml-env-tag, python-dateutil, pyquery, jinja2, importlib-metadata, beautifulsoup4, readtime, markdown, ghp-import, pymdown-extensions, mkdocs, mkdocs-material
Successfully installed MarkupSafe-2.1.3 babel-2.12.1 beautifulsoup4-4.12.2 certifi-2023.5.7 charset-normalizer-3.2.0 click-8.1.4 colorama-0.4.6 cssselect-1.2.0 ghp-import-2.1.0 idna-3.4 importlib-metadata-6.8.0 jinja2-3.1.2 lxml-4.9.3 markdown-3.3.7 markdown2-2.4.9 mergedeep-1.3.4 mkdocs-1.4.3 mkdocs-material-9.1.18+insiders.4.37.0 mkdocs-material-extensions-1.1.1 packaging-23.1 paginate-0.5.6 pipdeptree-2.9.4 pygments-2.15.1 pymdown-extensions-10.0.1 pyquery-2.0.0 python-dateutil-2.8.2 pytz-2023.3 pyyaml-6.0 pyyaml-env-tag-0.1 readtime-2.0.0 regex-2023.6.3 requests-2.31.0 six-1.16.0 soupsieve-2.4.1 urllib3-2.0.3 watchdog-3.0.0 zipp-3.15.0
(venv) squidfunk@squidfunk2020 /tmp/mkdocs-test $ mkdoce new .                            
(venv) squidfunk@squidfunk2020 /tmp/mkdocs-test $ mkdpcs n         
(venv) squidfunk@squidfunk2020 /tmp/mkdocs-test $ mkdocs new .                            
INFO     -  Writing config file: ./mkdocs.yml
INFO     -  Writing initial docs: ./docs/index.md
(venv) squidfunk@squidfunk2020 /tmp/mkdocs-test $ code .        
(venv) squidfunk@squidfunk2020 /tmp/mkdocs-test $ mkdocs serve --watch-theme --dirtyreload
INFO     -  Building documentation...
WARNING  -  A 'dirty' build is being performed, this will likely lead to inaccurate navigation and other links within your site. This option is designed for site development purposes only.
INFO     -  Documentation built in 0.35 seconds
INFO     -  [09:42:49] Watching paths for changes: 'docs', 'mkdocs.yml', 'venv/lib/python3.8/site-packages/material', 'venv/lib/python3.8/site-packages/mkdocs/templates'
INFO     -  [09:42:49] Serving on http://127.0.0.1:8000/
```

As you can see, all works with a clean install. Also, our build and my local installation work just fine. If you do a clean instal as well, does it work for you?

> Same goes for the built-in blog plugin

@ossinova In Insiders or in the community edition? What version are you using?

**Comment by ossinova** [comment]
Community edition, I build it yesterday (fresh install) and according to the docs the blog plugin is now open and not an insider feature.

**Comment by squidfunk** [comment]
@ossinova correct, [you currently need to install 9.2.0b0](https://github.com/squidfunk/mkdocs-material/issues/5686) 😊

**Comment by squidfunk** [comment]
I'm closing this issue as non-reproducible (for now). If you manage to create a reproduction that allows to observe what you're reporting, we'll reopen it. Make sure that you did not install Insiders in a different location than before. As I showed in https://github.com/squidfunk/mkdocs-material/issues/5695#issuecomment-1626898951, installing Insiders in a clean virtual environment works as expected. Possible help in debugging:

1. In the past, I tripped over the same problem when I forgot to activate the virtual environment before installing. If the error persists, execute the following and check if the correct version is installed:

    ```
    pip list
    ```

2. Make sure that you selected Material for MkDocs as a theme. In your OP, you're using configuration inheritance. It may be possible that the following is not set, which is essential for the built-in plugins to work:

    ``` yaml
    theme:
      name: material
    ```

3. Try to use the fully qualified name of the plugin:

    ``` yaml
    plugins:
      - material/meta
    ```

**Comment by squidfunk** [comment]
@discdiver Could you share what the problem was? This might be helpful for other users 😊

**Comment by discdiver** [comment]
I'd be happy to, but I'm not sure what it was. 🙂

**Comment by nandoflorestan** [comment]
As a senior Python developer, I am running into all sorts of difficulties as I try to create a blog.

Simply following the instructions in
https://squidfunk.github.io/mkdocs-material/blog/2022/09/12/blog-support-just-landed/
with mkdocs-material version 9.4.2
does not work at all.

This error message is the least informative ever:
ERROR   -  Config value 'plugins': Invalid Plugins configuration

Here are a few other error messages as I try different things:
ERROR   -  Config value 'plugins': The "meta" plugin is not installed
ERROR   -  Config value 'plugins': The "material/meta" plugin is not installed

The documentation does not tell me pip install any additional plugins.  I tried to find those, but there are hundreds and hundreds of packages for mkdocs.

Yes, I am running things inside my virtualenv.  Like I said, I am not green.  If you try to follow your own instructions, you will find them lacking.

**Comment by facelessuser** [comment]
@nandoflorestan replying to this closed issue is probably not appropriate. I would probably start with creating a discussion and providing a [minimal reproduction of your issue](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/?h=repro).

**Comment by squidfunk** [comment]
@nandoflorestan are you subscribed as a [sponsor](http://github.com/sponsors/squidfunk) and using [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/)? The [`meta` plugin](https://squidfunk.github.io/mkdocs-material/plugins/meta/) is currently reserved to sponsors, is built-in, and doesn't need to be installed (it's installed alongside Material for MkDocs), but only if you're using [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/).

The heart icon denotes that a feature is reserved to sponsors:

<img width="665" alt="Bildschirm­foto 2023-09-25 um 16 46 10" src="https://github.com/squidfunk/mkdocs-material/assets/932156/8c50cd44-aca5-4e47-829d-93a5811461d6">

**Comment by squidfunk** [comment]
Note that this article was written when the blog plugin was still reserved to sponsors. We'll remove the meta plugin from the configuration mentioned in the blog article to make it clearer. I agree that this might be confusing.

**Comment by francis2tm** [comment]
Hello @squidfunk 

```
plugins:
  - privacy
```
Results in

```
ERROR   -  Config value 'plugins': The "privacy" plugin is not installed
Aborted with 1 configuration errors!
ERROR   -  [14:25:29] An error happened during the rebuild. The server will appear stuck until build errors are resolved.
```
Fresh install. Any idea how to fix?

**Comment by squidfunk** [comment]
@francis2tm using [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/)? The privacy plugin is currently reserved to sponsors.

<img width="762" alt="Bildschirm­foto 2023-10-09 um 17 37 10" src="https://github.com/squidfunk/mkdocs-material/assets/932156/9c88d727-f1b3-4c4f-ad6b-501ad0722380">

**Comment by jm3** [comment]
FYI, I think the fact that the meta plugin is only for Insiders sponsors isn't as clear from the docs as you might think :)

I made the same mistake as others did above. Neither the docs article header nor the left navigation note that the meta plugin (which the docs clearly state is built in) is _restricted_ to insiders only. I have no issue with that decision, but it might save you and everyone some time if this distinction were a bit more prominent, e.g. at the top of the docs page (with an admonition / call-out) and/or in the left navigation (e.g. with the insiders / sponsors icon, or similar).

I would even suggest that noting that the plugin is "built in" (as the docs clearly state) runs counter to the goal of being clear to users that the plugin is only available to Insiders.

<img width="1264" alt="screenshots of docs page" src="https://github.com/squidfunk/mkdocs-material/assets/12213/b51247d1-0bba-45ed-92af-653e0a081ebe">

Just a suggestion, thanks for sharing a great open source project.

**Comment by squidfunk** [comment]
Thanks for the feedback. We heard the critique and added a banner to each plugin that is currently only available via Insiders in 4edce4349. I hope that this clarifies the situation and incentivizes people to support our work.

> I would even suggest that noting that the plugin is "built in" (as the docs clearly state) runs counter to the goal of being clear to users that the plugin is only available to Insiders:

Built-in means there is no installation or setup necessary, as opposed to third-party plugins. It was not copy-pasted. The plugin __is__ available, you only need to support our work by sponsoring it. If you do, you only need to add one line.

![screenshot-localhost-3000-mkdocs-material-plugins-meta-1700552433568](https://github.com/squidfunk/mkdocs-material/assets/932156/d2f95021-551b-4afc-b581-0f3471f39382)

**Comment by jm3** [comment]
Awesome! I think it's a win for usability and clarity, hopefully resulting in more sponsors now that it's a bit clearer up front that plugins like this `meta` get "unlocked" when becoming a sponsor. I appreciate it.
