### ISSUE TITLE
feedback widget configuration in page header (and .meta.yml!)

### ISSUE THREAD

**Issue by alexvoss** [squidfunk/mkdocs-material#6507]
### Context

While building a template for setting up a blog, I stumbled across possible use cases that involve having different feedback questions configured in different parts of a site or different notes that appear in response. For example, for documentation pages we may want to ask if they are "helpful" but for blog posts we might ask if they are "interesting" or, perhaps, "informative".

### Description

I am therefore proposing that we change the feedback partial so that it takes a configuration from the page header if there is one, overwriting what is configured in `mkdocs.yml`. This allows custom behaviour on a per-page basis. 

Now comes the kicker: with the help of the meta plugin, sponsors could define this custom behaviour more elegantly for whole sections of their site. IMHO a wonderful use case for the meta plugin. (The functionality would become available to all with the next funding goal.)

The change should be trivial, just adding in the following to the `feedback.html` partial:

```
<!-- Override if feedback is set in page -->
{% if page.meta and page.meta.feedback %}
  {% set feedback = page.meta.feedback %}
{% endif %}
```

Hope I am understanding the workings Jinja, the page header and the meta plugin correctly here! I tested it on the Material for MkDocs documentation and it seemed to work as I expected, see visuals below.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics#was-this-page-helpful

### Use Cases

- asking feedback questions that are more in line with the content of a page
- providing different notes in response to the feedback, again matching the page content

### Visuals

![image](https://github.com/squidfunk/mkdocs-material/assets/4134224/18aa227b-dd6b-48f0-9aff-69690426e84d)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. So as I understand, users would be able to influence everything that is settable via [`extra.analytics.feedback`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#was-this-page-helpful), right? Why not put it under `analytics.feedback` then? We already have so many supported front matter properties, we should need to come up with a ordering concept before we add more to them. I think we should come up with a plan how and where we add further functionalities in front matter before we do. What do you think?

**Comment by alexvoss** [comment]
> under `analytics.feedback`

there is certainly an argument to be made for consistency, avoiding possible name clashes and avoiding surprises. By the last bit I mean: if someone who is not the original author looks at a page, they should be able to easily figure out what the setting is. Knowing where to look in the documentation helps and here the `analytics` part would help.

**Comment by squidfunk** [comment]
I'm closing this issue with the imperative that need to go back to the drawing board. Let's work our a solid proposal how we can classify which settings can be made configurable per page, and how we can find a taxonomy and syntax to pull that off. It's research, and far beyond what's requested in this OP, so I'm closing this for now.

Let's create an (internal?) discussion for this first.
