### ISSUE TITLE
Front matter meta should override .meta.yml defaults 

### ISSUE THREAD

**Issue by rachel-rigdon-sp** [squidfunk/mkdocs-material#6914]
### Context

I am adding a Discourse comments section to our documentation. I've set the .meta.yml to comments: true and placed it in our docs/ folder, which successfully applied the comments.html override with the Discourse code to all pages in the folder.

However, there are some pages within the folder (like our main index.md) that we don't want comments on.

I've tried excluding them using meta formatting at the top, like:

```
---
comments: false
---
```
I've also tried `comments: hide` and `comments: exclude` on the individual page, to no avail.

### Description

Make the front matter you set on individual pages override the defaults in the .meta.yml

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- https://github.com/squidfunk/mkdocs-material/discussions/6913
- https://squidfunk.github.io/mkdocs-material/plugins/meta/

### Use Cases

Author's: 

- Have more fine-grained control over which pages should include/exclude comments, tags, and blog configurations by prioritizing the front matter over the .meta.yml defaults. 
- Be able to include/exclude features without creating a hook. 

User's - Will only see features that are useful for specific pages, which can declutter docs and direct focus to the right content.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for reporting. Indeed, this sounds like unintended behavior! I'll investigate.

**Comment by squidfunk** [comment]
Fixed in [`ef7c754a9`](https://github.com/squidfunk/mkdocs-material-insiders/commit/ef7c754a9e076bcab726e71ce350f9b9d3ff8094). This commit changes the meta plugin in that the page metadata is merged last, so that it always takes precedence over any meta files, which should solve the reported problem. I can't be sure, as there's no reproduction attached to this issue, but my testing shows that it should work now. If not, please provide a minimal reproduction.

The meta plugin offers some opportunities for refactoring, which we'll revisit in the future. Feedback like this one is very valuable, so we can decide which direction we need to take it to be as useful as possible ☺️

**Comment by squidfunk** [comment]
Released as part of [9.5.14+insiders-4.53.2](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.53.2).

**Comment by rachel-rigdon-sp** [comment]
@squidfunk Thank you so much! It's working perfectly! I super appreciate your speedy response and fix. 🙌🏻
