### ISSUE TITLE
Meta: duplicate entries in front matter lists

### ISSUE THREAD

**Issue by vicmteam** [squidfunk/mkdocs-material#6941]
### Context

Environment info:
```
mkdocs-material==9.5.14+insiders.4.53.2
mkdocs-material-extensions==1.3.1
```

### Bug description

The `links` metadata in the blog is added twice to the sidebar, see:

![grafik](https://github.com/squidfunk/mkdocs-material/assets/129054846/ec37a861-2026-456c-baee-dc68acc0562b)

### Related links

- [Example](https://squidfunk.github.io/mkdocs-material/blog/2022/05/05/chinese-search-support/)
- [Documentation of the feature](https://squidfunk.github.io/mkdocs-material/plugins/blog/#meta.links)

### Reproduction

Not relevant, since the bug also appears in the official documentation (see link above).

### Steps to reproduce

1. Define a `links` metadata on a blog post.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. If you want it fixed, you can help us by providing minimal reproduction. Otherwise, we need to do it, so you would actively help us fixing it faster. Thank you!

**Comment by squidfunk** [comment]
We need to rely a little on our users to help us recreate the conditions in which we can observe and fix errors, so a minimal reproduction is always mandatory when filing a bug report ☺️ Thanks for providing one so quickly and debugging it! It is definitely a regression of [9.5.14-insiders-4.53.2](https://github.com/squidfunk/mkdocs-material-insiders/releases/tag/9.5.14-insiders-4.53.2). Temporary mitigation: downgrade to [9.5.14-insiders-4.53.1](https://github.com/squidfunk/mkdocs-material-insiders/releases/tag/9.5.14-insiders-4.53.1).

**Comment by squidfunk** [comment]
No need – yes, it is a bug in Insiders, but we track all bugs in the public issue tracker. The idea is to have a single place for change requests, bug reports and questions. Insiders is not a gated community.

**Comment by squidfunk** [comment]
Fixed in [`84d19b8`](https://github.com/squidfunk/mkdocs-material-insiders/commit/84d19b8f7b7951ccbc44e31ac5ab9da397fbb1dc).

**Comment by squidfunk** [comment]
Released as part of [9.5.15+insiders-4.53.3](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.53.3).
