### ISSUE TITLE
Meta plugin duplicates YAML frontmatter values

### ISSUE THREAD

**Issue by Guts** [squidfunk/mkdocs-material#6943]
### Bug description

When the meta plugin is enabled, the page metadata seems to be duplicated. I realized this because I use the value of `authors` to add tags in the extrahead block.

That's why I took the liberty of including a theme customization in the reproduction.

### Related links

- https://squidfunk.github.io/mkdocs-material/plugins/meta/

Potential related issues:

- possible cause: https://github.com/squidfunk/mkdocs-material/issues/6914 in https://github.com/squidfunk/mkdocs-material-insiders/commit/ef7c754a9e076bcab726e71ce350f9b9d3ff8094
- other consequence: https://github.com/squidfunk/mkdocs-material/issues/6941

### Reproduction

[9.5.14+insiders.4.53.2-meta-plugin-duplicates-frontmatter.zip](https://github.com/squidfunk/mkdocs-material/files/14673280/9.5.14%2Binsiders.4.53.2-meta-plugin-duplicates-frontmatter.zip)

### Steps to reproduce

1. Enable meta plugin and add some authors in YAML frontmatter:

    ```markdown
    ---
    authors:
        - Martin
    ---

    # Welcome to MkDocs

    [...]
    ```

1. Use this variable somewhere, for example in a template extension:

    ```jinja-html
    {% for a in page.meta.authors %}
      {% if page_author != config.site_author %}
        <meta name="author" content="{{ a }}">
      {% endif %}
    {% endfor %}

    ```

1. mkdocs build
1. result:

```html
<head>
[...]
<meta name="author" content="Martin">
<meta name="author" content="Martin">
[...]
</head>
```

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by Guts** [comment]
> possible cause: Front matter meta should override .meta.yml defaults  #6914 in https://github.com/squidfunk/mkdocs-material-insiders/commit/ef7c754a9e076bcab726e71ce350f9b9d3ff8094

I confirm that getting back to [mkdocs-material-9.5.13-insiders-4.53.1](https://github.com/squidfunk/mkdocs-material-insiders/releases/tag/9.5.13-insiders-4.53.1) is "solving" the issue.

**Comment by squidfunk** [comment]
Thanks for reporting. This is a duplicate of #6941.
